"""migrations

Revision ID: 05aaaed5698a
Revises: 4fd7a0258672
Create Date: 2019-06-03 11:52:59.474682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05aaaed5698a'
down_revision = '4fd7a0258672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_category_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'category_id')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_category_id_fkey', 'blogs', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
