"""second migration

Revision ID: cd7b8a904720
Revises: 05aaaed5698a
Create Date: 2019-06-03 11:55:21.246422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7b8a904720'
down_revision = '05aaaed5698a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'category_id')
    # ### end Alembic commands ###
